/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fichajespi.fichajespidestopapp;

import com.fichajespi.fichajespidestopapp.smartcard.CardReader;
import com.fichajespi.fichajespidestopapp.tools.CurrentDate;
import com.fichajespi.fichajespidestopapp.tools.CurrentTime;
import javax.swing.JFrame;

/**
 *
 * @author alex
 */
public class MainWindow extends javax.swing.JFrame {

  /**
   * Creates new form MainWindow2
   */
  public MainWindow() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabelFichaje = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabelNombre = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabelHora = new javax.swing.JLabel();
    jLabelDate = new javax.swing.JLabel();
    jLabelNumero = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("FichajesPi");
    setBackground(new java.awt.Color(255, 51, 102));
    setLocation(new java.awt.Point(0, 0));
    setLocationByPlatform(true);
    setMinimumSize(new java.awt.Dimension(480, 320));
    setName("FichajesPi"); // NOI18N
    setUndecorated(true);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(210, 23, 87));

    jLabelFichaje.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
    jLabelFichaje.setForeground(new java.awt.Color(255, 255, 255));
    jLabelFichaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelFichaje.setText("Acerque tarjeta al lector");

    jLabel1.setFont(new java.awt.Font("SansSerif", 0, 35)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("FichajesPi");
    jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel1MouseClicked(evt);
      }
    });

    jLabelNombre.setFont(new java.awt.Font("sansserif", 0, 35)); // NOI18N
    jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
    jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelNombre.setText("Esperando...");

    jPanel2.setBackground(new java.awt.Color(105, 186, 201));

    jLabelHora.setBackground(new java.awt.Color(255, 255, 204));
    jLabelHora.setFont(new java.awt.Font("sansserif", 1, 34)); // NOI18N
    jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
    jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelHora.setText("00:00");

    jLabelDate.setFont(new java.awt.Font("sansserif", 0, 25)); // NOI18N
    jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
    jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelDate.setText("dia");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(17, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
          .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabelNumero.setFont(new java.awt.Font("sansserif", 0, 25)); // NOI18N
    jLabelNumero.setForeground(new java.awt.Color(204, 204, 204));
    jLabelNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelNumero.setText("--");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(22, 22, 22))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelFichaje, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabelNombre)
        .addGap(18, 18, 18)
        .addComponent(jLabelFichaje)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
        .addComponent(jLabelNumero)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

        private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
//Not minimizing anymore
//		setState(JFrame.ICONIFIED);
        }//GEN-LAST:event_jLabel1MouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        MainWindow mw = new MainWindow();
        mw.setVisible(true);

        mw.resetScreen();

        CurrentTime updateTime = new CurrentTime(mw);
        updateTime.start();

        CurrentDate updateDate = new CurrentDate(mw);
        updateDate.start();

        new CardReader(mw).start();

        /*
				Scanner scanner = new Scanner(System.in);
				while (true) {
					String numeroEmpleado = scanner.next();
					Fichaje fichaje = RequestSender.sendRequest(numeroEmpleado);
					if (fichaje != null) {
						System.out.println(fichaje.getNombreUsuario());
					}
				}*/
      }
    });
  }

  public void changeTime(String hora) {
    jLabelHora.setText(hora);
  }

  public void changeDate(String date) {
    jLabelDate.setText(date);
  }

  public void changeNombre(String nombre) {
    jLabelNombre.setText(nombre);
  }

  public void changeFichaje(String fichaje) {
    jLabelFichaje.setText(fichaje);
  }

  public void changeNumero(String numero) {
    jLabelNumero.setText(numero);
  }

  public void resetScreen() {
    jLabelNombre.setText("Esperando...");
    jLabelFichaje.setText("Acerque su tarjeta...");
    jLabelNumero.setText("");
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabelDate;
  private static javax.swing.JLabel jLabelFichaje;
  private static javax.swing.JLabel jLabelHora;
  private static javax.swing.JLabel jLabelNombre;
  private javax.swing.JLabel jLabelNumero;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
