FROM maven:3.8.4-jdk-11-slim AS build 
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package -DskipTests

FROM openjdk:11-slim-buster
COPY --from=build "home/app/target/fichajesPi.backend-0.0.1-SNAPSHOT.jar" "app.jar"
ENTRYPOINT ["java","-jar","app.jar"]
